language: php
php:
  - 5.5
  - 5.4
before_script:
    - composer install --dev
after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage
script: ./bin/phpspec run --format pretty
